[package]
name = "make-value"
version = "1.0.0"
authors = ["Jaguar-515 <j.aguar.515.515@gmail.com>"]
edition = "2018"

[dependencies]
clap = "2.33.1"
rbx_dom_weak = "1.10.1"
rbx_xml = "0.11.4"
rbx_binary = "0.5.0"
maplit = "1.0.2"